server:
  port: ${PORT:8080}

spring:
  data:
    mongodb:
      uri: ${MONGODB_URL:mongodb://localhost:27017}


uno:
  board-game:
    base-url: https://shivi-board-games-backend.herokuapp.com
    path: /users
